routes/web.php
<?php

use App\Http\Controllers\Blog\PostsController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'WelcomeController@index')->name('welcome');
//Route::get('/posts/{post}', [PostsController::class, 'show'])->name('blog.show'); // ini akan overwrite bagian 'Route::resource('posts', 'PostsController');', jadi tidak disarankan
Route::get('blog/posts/{post}', [PostsController::class, 'show'])->name('blog.show');
//Route::get('blog/posts/{post}', 'Blog\PostsController@show')->name('blog.show');
Route::get('blog/categories/{category}', [PostsController::class, 'category'])->name('blog.category');
Route::get('blog/tags/{tag}', [PostsController::class, 'tag'])->name('blog.tag');

Auth::routes();

//Route::group(function () {
Route::middleware(['auth'])->group(function () {

    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('categories', 'CategoriesController'); // 'resources' tanpa method
    //Route::resource('posts', 'PostsController')->middleware(['auth', 'verifyCategoriesCount']); // jika seperti ini, maka semua resource yang berhubungan dengan posts akan dicek
    //Route::resource('posts', 'PostsController')->middleware('auth');
    Route::resource('posts', 'PostsController');
    Route::resource('tags', 'TagsController');
    Route::get('trashed-post', 'PostsController@trashed')->name('trashed-posts.index');
    Route::put('restore-post/{post}', 'PostsController@restore')->name('restore-posts');

});

Route::middleware(['auth', 'admin'])->group(function () {
    Route::get('users/profile', 'UsersController@edit')->name('users.edit-profile');
    Route::put('users/profile', 'UsersController@update')->name('users.update-profile'); // karena update, jadi pakai 'put'
    Route::get('users', 'UsersController@index')->name('users.index');
    Route::post('users/{user}/make-admin', 'UsersController@makeAdmin')->name('users.make-admin');
    Route::post('users/{user}/make-writer', 'UsersController@makeWriter')->name('users.make-writer');
});

app/Tag.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    protected $fillable = ['name'];

    // Define relationship with table 'posts'
    public function posts()
    {
        return $this->belongsToMany(Post::class); // many to many relationship, 1 post bisa banyak tag & 1 tag bisa banyak post
    }
}

app/Http/Controllers/TagsController.php
<?php

namespace App\Http\Controllers;

use App\Tag;
use Illuminate\Http\Request;
use App\Http\Requests\Tags\CreateTagRequest;
use App\Http\Requests\Tags\UpdateTagRequest;

class TagsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //dd(Tag::first()->posts); // menampilkan array of object melalui collection
        //dd(Tag::first()->posts()); // menampilkan relationship-nya
        //dd(Tag::first()->posts()->where('published_at', now())->get()); // menampilkan collection saja
        //dd(Tag::first()->posts()->where('published_at', now())); // menampilkan relationship-nya sekarang
        //dd(Tag::first()->posts()->get()); // array of results (collection)
        //dd(Tag::first()->posts());//array of results (collection) that belongs to this Tag

        return view('tags.index')->with('tags', Tag::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('tags.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateTagRequest $request)
    {
        //$this->validate(request()); // tidak efisien
        //$this->validate($request, [
        //    'name'=>'required|unique:tags'
        //]);


        //LEBIH AMAN MEMAKAI INI
        //$ntag = new Tag();
        Tag::create([
            'name' => $request->name
        ]);

        session()->flash('success', 'Tag created successfully.');

        /*TIDAK DISARANKAN MEMAKAI INI
        Tag::create($request->all());
        */

        //return redirect('/Tags');
        return redirect(route('tags.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Tag $tag) // memakai route model binding
    {
        return view('tags.create')->with('tag', $tag);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateTagRequest $request, Tag $tag)
    {
        $tag->update([
            'name' => $request->name
        ]);
        //$Tag->name=$request->name;
        //$Tag->save();

        session()->flash('success', 'Tag updated successfully.');

        return redirect(route('tags.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Tag $tag)
    {
        // mengecek apakah tag memiliki post atau tidak
        if ($tag->posts->count() > 0) {
            session()->flash('error', 'Tag cannot be deleted, because there are posts related to it.');
            return redirect()->back();
        }

        $tag->delete();

        session()->flash('success', 'Tag delete successfully.');

        return redirect(route('tags.index'));
    }
}

resources/views/tags/create.blade.php
@extends('layouts.app')


@section('content')

    <div class="card card-default">
        <div class="card-header text-center">
            <h3>
            {{ isset($tag) ? 'EDIT CURRENT TAG' : 'CREATE NEW TAG' }} <!-- isset dipakai karena tag hanya akan tersedia ketika user memilih 'Edit' -->
            </h3>
        </div>
        <div class="card-body">

            @include('partials.errors')

            <form
                action="{{ isset($tag) ? route('tags.update', $tag->id) : route('tags.store') }}"
                method="POST">
                @csrf
                @if(isset($tag))
                    @method('PUT')
                @endif
                <div class="form-group">
                    <label for="name"><b>Name</b></label>
                    <input type="text" id="name" class="form-control" name="name"
                           value="{{ isset($tag) ? $tag->name : '' }}">
                </div>

                <div class="form-group">
                    <button type="submit" class="btn btn-success mx-2" style="float: right;"><i class="fa fa-save"></i>
                        {{ isset($tag) ? ' Finish Updating Tag' : ' Finish Creating Tag'}}
                    </button>
                </div>

                <div class="form-group">
                    <a href="{{ route('tags.index') }}" class="btn btn-dark mx-2" style="float: right;"><i class="fa fa-times"></i>
                        Cancel
                    </a>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/tags/index.blade.php
@extends('layouts.app')


@section('content')

    <div class="d-flex justify-content-end">
        <!-- <a href="/tags/create" class="btn btn-success float-right mb-2">Add tag</a> -->
        <a href="{{ route('tags.create') }}" class="btn btn-success float-right mb-2"><i class="fa fa-plus"></i> Add Tag</a>
    </div>

    <div class="card card-default">
        <div class="card-header">Tags</div>
        <div class="card-body">
            @if($tags->count()>0)
                <table class="table">
                    <thead>
                    <th>Tags Name</th>
                    <th>Total Posts</th>
                    <th>Action</th>
                    </thead>
                    <tbody>
                    @foreach($tags as $tag)
                        <tr>
                            <td>
                                {{ $tag->name }}
                            </td>
                            <td>
                                {{ $tag->posts->count() }}

                                {{-- menampilkan array = {{ $tag->posts }} --}}
                                {{-- perlu dd di TagsController bagian index = {{ $tag->posts() }} --}}

                            </td>
                            <td>
                                <a href="{{ route('tags.edit', $tag->id) }}" class="btn btn-info btn-sm"
                                   style="color:white"><i class="fa fa-edit"></i> Edit</a>

                                <!-- Pakai '$tag->id' dikarenakan di tengah lokasinya ada '{tag}', versi lengkapnya 'tags/{tag}/edit' -->

                                <button class="btn btn-danger btn-sm" onclick="handleDelete({{ $tag->id }})">
                                    <i class="fa fa-trash-o"></i>
                                     Delete
                                </button>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            @else
                <h3 class="text-center">No tags yet.</h3>
        @endif

        <!-- START MODAL EXAMPLE CODE -->

            <form action="" method="POST" id="deleteTagForm">
            @csrf
            @method('DELETE')
            <!-- Modal -->
                <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
                     aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="deleteModalLabel">Delete Tag</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <p class="text-center text-bold">
                                    Are you sure to delete this tag?
                                </p>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">No, go back.
                                </button>
                                <button type="submit" class="btn btn-danger">Yes, delete.</button>
                            </div>
                        </div>
                    </div>
                </div>

            </form>

            <!-- END MODAL EXAMPLE CODE -->

        </div>
    </div>
    </div>
@endsection

@section('scripts')
    <!-- JAVASCRIPT START -->
    <script>
        function handleDelete(id) {
            var form = document.getElementById('deleteTagForm')
            form.action = '/tags/' + id
            //console.log('Deleting', form)
            $('#deleteModal').modal('show')
        }
    </script>
    <!-- JAVASCRIPT END-->
@endsection