routes/web.php
<?php

use App\Http\Controllers\Blog\PostsController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'WelcomeController@index')->name('welcome');
//Route::get('/posts/{post}', [PostsController::class, 'show'])->name('blog.show'); // ini akan overwrite bagian 'Route::resource('posts', 'PostsController');', jadi tidak disarankan
Route::get('blog/posts/{post}', [PostsController::class, 'show'])->name('blog.show');
//Route::get('blog/posts/{post}', 'Blog\PostsController@show')->name('blog.show');
Route::get('blog/categories/{category}', [PostsController::class, 'category'])->name('blog.category');
Route::get('blog/tags/{tag}', [PostsController::class, 'tag'])->name('blog.tag');

Auth::routes();

//Route::group(function () {
Route::middleware(['auth'])->group(function () {

    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('categories', 'CategoriesController'); // 'resources' tanpa method
    //Route::resource('posts', 'PostsController')->middleware(['auth', 'verifyCategoriesCount']); // jika seperti ini, maka semua resource yang berhubungan dengan posts akan dicek
    //Route::resource('posts', 'PostsController')->middleware('auth');
    Route::resource('posts', 'PostsController');
    Route::resource('tags', 'TagsController');
    Route::get('trashed-post', 'PostsController@trashed')->name('trashed-posts.index');
    Route::put('restore-post/{post}', 'PostsController@restore')->name('restore-posts');

});

Route::middleware(['auth', 'admin'])->group(function () {
    Route::get('users/profile', 'UsersController@edit')->name('users.edit-profile');
    Route::put('users/profile', 'UsersController@update')->name('users.update-profile'); // karena update, jadi pakai 'put'
    Route::get('users', 'UsersController@index')->name('users.index');
    Route::post('users/{user}/make-admin', 'UsersController@makeAdmin')->name('users.make-admin');
    Route::post('users/{user}/make-writer', 'UsersController@makeWriter')->name('users.make-writer');
});

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Post extends Model
{
    use SoftDeletes;

////    protected $dates = [
////        'published_at'
////    ];

    protected $fillable = [
        'title', 'description', 'content', 'image', 'published_at', 'category_id', 'user_id'
    ];

    /**
     * Delete post image from storage
     *
     * @return void
     */
    public function deleteImage()
    {
        \Storage::delete($this->image);
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
        //return $this->belongsTo('App\Category');
    }

    // Define a relationship with table 'tags'
    public function tags() // plural = dengan huruf s diakhir, karena banyak
    {
        return $this->belongsToMany(Tag::class);
    }

    /**
     * check if post has tag
     * @param $tagId
     * @return bool
     */
    public function hasTag($tagId) // define relationship
    {
        return in_array($tagId, $this->tags->pluck('id')->toArray());
    }

    public function user() // define relationship mirip category dengan post
    {
        return $this->belongsTo(User::class);
    }

    public function scopeSearched($query) // method ini dipanggil dengan menulis 'searched()'
    {
        //$query->where();
        //$query->category(); // relationship, karena query model
        $search = request()->query('search');

        if (!$search) {
            ////return $query->published();
            return $query;
        }

        ////return $query->published()->where('title', 'LIKE', "%{$search}%");
        return $query->where('title', 'LIKE', "%{$search}%");
    }

////    public function scopePublished($query)
////    {
////        return $query->published()->where('published_at', '<=', now());
////    }
}

app/Http/Controllers/Blog/PostsController.php
<?php

namespace App\Http\Controllers\Blog;

use App\Tag;
use App\Post;
use App\Category;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;


class PostsController extends Controller
{
    public function show(Post $post)
    {
        return view('blog.show')
            ->with('post', $post);
    }

    public function category(Category $category)
    {
//        $search = request()->query('search');
//        if ($search) {
//            $posts = $category->posts()
//                ->where('title', 'LIKE', "%($search)%")->simplePaginate(4);
//        } else {
//            $posts = $category->posts()->simplePaginate(4);
//        }


        return view('blog.category')
            ->with('category', $category)
            //->with('posts', $category->posts()->simplePaginate(4))
            //->with('posts', $posts)
            ->with('posts', $category->posts()->searched()->simplePaginate(4))
            ->with('categories', Category::all())
            ->with('tags', Tag::all());
    }

    public function tag(Tag $tag)
    {
        return view('blog.tag')
            ->with('tag', $tag)
            //->with('posts', $tag->posts()->simplePaginate(4))
            ->with('posts', $tag->posts()->searched()->simplePaginate(4))
            ->with('categories', Category::all())
            ->with('tags', Tag::all());
    }
}

app/Http/Controllers/PostsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\Posts\CreatePostRequest;
use App\Http\Requests\Posts\UpdatePostRequest;
use App\Post;
use App\Category;
use App\Tag;

use Storage;

//use Illuminate\Support\Facades\Storage;

class PostsController extends Controller
{
    // membuat constructor baru
    public function __construct()
    {
        $this->middleware('verifyCategoriesCount')->only(['create', 'store']); // only adalah method
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('posts.index')->with('posts', Post::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('posts.create')->with('categories', Category::all())->with('tags', Tag::all());
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreatePostRequest $request) // Memakai route model binding
    {
        // upload image
        // dd($request->image->store('posts'));
        // dd($request->all());

        $image = $request->image->store('posts');

        // create post
        $post = Post::create([
            'title' => $request->title,
            'description' => $request->description,
            'content' => $request->content,
            'image' => $image,
            'published_at' => $request->published_at,
            'category_id' => $request->category,
            'user_id' =>auth()->user()->id // untuk user yang membuat postingan
        ]);

        if ($request->tags) {
            $post->tags()->attach($request->tags); // attach() karena belongsToMany
        }

        // flash message
        session()->flash('success', 'Post created successfully');

        // redirect user
        return redirect(route('posts.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        //dd($post->tags->pluck('id')->toArray());
        return view('posts.create')->with('post', $post)->with('categories', Category::all())->with('tags', Tag::all());
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdatePostRequest $request, Post $post)
    {
        // $data=$request->all();
        $data = $request->only(['title', 'description', 'content', 'category_id', 'published_at']);
        // check if new image
        if ($request->hasFile('image')) {

            // upload it
            $image = $request->image->store('posts');

            // delete old one
            //Storage::delete($post->image); // perlu route model binding 'Post $post'
            $post->deleteImage();
            $data['image'] = $image;
        }

        // cek jika user memilih tag yang berbeda dari yang sebelumnya dalam editing
        if ($request->tags) {
            $post->tags()->sync($request->tags);
        }

        // update attribute
        $post->update($data);

        // flash message
        session()->flash('success', 'Post updated successfully.');

        // redirect user
        return redirect(route('posts.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $post = Post::withTrashed()->where('id', $id)->firstOrFail(); // method 'firstOrFail()' akan melempar eksepsi (404) jika record tidak ada di DB

        if ($post->trashed()) {
            //Storage::delete($post->image);
            $post->deleteImage();
            $post->forceDelete();
            session()->flash('success', 'Post permanently deleted.');
        } else {
            $post->delete();
            session()->flash('success', 'Post moved to trash successfully.');
        }

        return redirect()->back();
    }

    /**
     * Display a list from deleted posts that move in trash
     *
     * @return \Illuminate\Http\Response
     */

    public function trashed()
    {
        //$trashed=Post::withTrashed()->get(); // fetch seluruh post
        $trashed = Post::onlyTrashed()->get(); // fetch trashed post saja
        //return view('posts.index')->withPosts($trashed);
        return view('posts.index')->with('posts', $trashed);
    }

    public function restore($id)
    {
        $post = Post::withTrashed()->where('id', $id)->firstOrFail();
        $post->restore();

        session()->flash('success', 'Post has been restored successfully.');

        return redirect()->back();
    }
}

resources/views/posts/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="card card-default">
        <div class="card-header" style="text-align: center">
            <h3>
                {{ isset($post) ? 'EDIT CURRENT POST'  : 'CREATE NEW POST' }}
            </h3>
        </div>

        <div class="card-body">

        @include('partials.errors')

        <!-- <form action="{{ route('posts.store') }}" method="POST" enctype="multipart/form-data"> -->
            <form action="{{ isset($post) ? route('posts.update', $post->id) : route('posts.store') }}" method="POST"
                  enctype="multipart/form-data">
                @csrf

                @if(isset($post))
                    @method('PUT')
                @endif

                <div class="form-group">
                    <label for="title"><b>Title</b></label>
                    <input type="text" class="form-control" name="title" id="title"
                           value="{{ isset($post) ? $post->title : '' }}">
                </div>

                <div class="form-group">
                    <label for="description"><b>Description</b></label>
                    <textarea name="description" id="description" cols="5" rows="5"
                              class="form-control">{{ isset($post) ? $post->description : '' }}</textarea>
                </div>

                <div class="form-group">
                    <label for="content"><b>Content</b></label>
                    <!-- <textarea name="content" id="content" cols="5" rows="5" class="form-control"></textarea> -->
                    <input id="content" type="hidden" name="content" value="{{ isset($post) ? $post->content:'' }}">
                    <trix-editor input="content"></trix-editor>
                </div>

                @if(isset($post))
                    <div class="form-group">
                        <img src="{{ URL::asset('storage/'.$post->image) }}" alt="" style="width:100%">
                    </div>
                @endif

                <div class="form-group">
                    <label for="image"><b>Image</b></label>
                    <input type="file" class="form-control" name="image" id="image">
                </div>

                <div class="form-group">
                    <label for="category"><b>Category</b></label>
                    <select name="category" id="category" class="form-control">
                        @foreach($categories as $category)
                            <option value="{{ $category->id }}"

                                    @if(isset($post))
                                    @if($category->id == $post->category_id)
                                    selected
                                @endif
                                @endif

                            >

                                {{ $category->name }}</option>
                        @endforeach
                    </select>
                </div>

                <!-- karena tag tidak wajib, maka hanya ditampilkan jika > 0-->
                @if($tags->count()>0)
                    <div class="form-group">
                        <label for="tags"><b>Tags</b></label>
                        <select name="tags[]" id="tags" class="form-control tags-selector" multiple>
                            @foreach($tags as $tag)
                                <option value="{{ $tag->id }}"
                                        @if(isset($post))

                                        {{-- hanya ditampilkan saat melakukan edit, bukan create --}}
                                        {{-- semua 'tags' dikonversi ke array, karena DB default return record data dalam bentuk collections --}}
                                        {{-- @if(in_array($tag->id, $post->tags->toArray())) --}}

                                        @if($post->hasTag($tag->id))
                                        selected
                                    @endif
                                    {{-- @endif --}}
                                    @endif
                                >

                                    {{ $tag->name }}
                                </option>
                            @endforeach
                        </select>
                    </div>
                @endif

                <div class="form-group">
                    <label for="published_at"><b>Published At</b></label>
                    <input type="text" class="form-control" name="published_at" id="published_at"
                           value="{{ isset($post) ? $post->published_at : '' }}">
                </div>

                <div class="form-group">
                    <button type="submit" class="btn btn-success mx-2" style="float: right;"><i class="fa fa-save"></i>
                        {{ isset($post) ? ' Finish Updating Post' : ' Finish Creating Post' }}
                    </button>
                </div>

                <div class="form-group">
                    <a href="{{ route('posts.index') }}" class="btn btn-dark mx-2" style="float: right;"><i class="fa fa-times"></i>
                        Cancel
                    </a>
                </div>

        </div>
        </form>
    </div>
    </div>
@endsection

@section('scripts')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.1/trix.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.0.12/dist/js/select2.min.js"></script>
    <script>
        flatpickr('#published_at', {
            enableTime: true,
            enableSeconds: true
        })

        $(document).ready(function () {
            $('.tags-selector').select2(); //'.tags-selector' adalah class
        });

    </script>
@endsection

@section('css')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.1/trix.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.0.12/dist/css/select2.min.css" rel="stylesheet"/>
@endsection

resources/views/posts/index.blade.php
@extends('layouts.app')

@section('content')

    @if(Route::current()->getName() != 'trashed-posts.index')
        <div class="d-flex justify-content-end">
            <a href="{{ route('posts.create') }}" class="btn btn-success float-right mb-2"><i class="fa fa-plus"></i>
                Add Post</a>
        </div>
    @endif

    <div class="card card-default">
        <div class="card-header">
            Posts
        </div>
        <div class="card-body">
            @if($posts->count()>0)
                <table class="table">
                    <thead>
                    <th>Image</th>
                    <th>Title</th>
                    <th>Category</th>
                    <th>Action</th>
                    </thead>
                    <tbody>
                    @foreach ($posts as $post)
                        <tr>
                            <td>
                                <img src="{{ asset('storage/'.$post->image) }}" width="120px" height="80px"
                                     alt="Gambar Postingan">
                            </td>
                            <td>
                                {{ $post->title }}
                            </td>
                            <td>
                                <a href="{{ route('categories.edit', $post->category->id) }}">
                                {{ $post->category->name }} <!-- category diambil dari 'Post.php' di bagian 'public function category()' -->
                                </a>
                            </td>
                            <td>
                                <div align="center" style="display:flex">
                                    @if(!$post->trashed())
                                        <a href="{{ route('posts.edit', $post->id) }}"
                                           class="btn btn-info btn-sm my-2 mx-2"><i class="fa fa-edit"></i> Edit</a>
                                    @else
                                        <form action="{{ route('restore-posts', $post->id) }}" method="POST">
                                            @csrf
                                            @method('PUT')
                                            <button type="submit" class="btn btn-secondary btn-sm my-2 mx-2"><i
                                                    class="fa fa-recycle"></i> Restore
                                            </button>
                                        </form>
                                    @endif

                                    <form action="{{ route('posts.destroy', $post->id) }}" method="POST">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-danger btn-sm my-2 mx-2">
                                            <i class="fa fa-trash-o"></i>
                                            {{ $post->trashed() ? "Delete" : "Trash" }}
                                        </button>
                                    </form>
                                </div>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            @else
                <h3 class="text-center">No posts yet.</h3>
            @endif
        </div>
    </div>
@endsection