routes/web.php
<?php

use App\Http\Controllers\Blog\PostsController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'WelcomeController@index')->name('welcome');
//Route::get('/posts/{post}', [PostsController::class, 'show'])->name('blog.show'); // ini akan overwrite bagian 'Route::resource('posts', 'PostsController');', jadi tidak disarankan
Route::get('blog/posts/{post}', [PostsController::class, 'show'])->name('blog.show');
//Route::get('blog/posts/{post}', 'Blog\PostsController@show')->name('blog.show');
Route::get('blog/categories/{category}', [PostsController::class, 'category'])->name('blog.category');
Route::get('blog/tags/{tag}', [PostsController::class, 'tag'])->name('blog.tag');

Auth::routes();

//Route::group(function () {
Route::middleware(['auth'])->group(function () {

    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('categories', 'CategoriesController'); // 'resources' tanpa method
    //Route::resource('posts', 'PostsController')->middleware(['auth', 'verifyCategoriesCount']); // jika seperti ini, maka semua resource yang berhubungan dengan posts akan dicek
    //Route::resource('posts', 'PostsController')->middleware('auth');
    Route::resource('posts', 'PostsController');
    Route::resource('tags', 'TagsController');
    Route::get('trashed-post', 'PostsController@trashed')->name('trashed-posts.index');
    Route::put('restore-post/{post}', 'PostsController@restore')->name('restore-posts');

});

Route::middleware(['auth', 'admin'])->group(function () {
    Route::get('users/profile', 'UsersController@edit')->name('users.edit-profile');
    Route::put('users/profile', 'UsersController@update')->name('users.update-profile'); // karena update, jadi pakai 'put'
    Route::get('users', 'UsersController@index')->name('users.index');
    Route::post('users/{user}/make-admin', 'UsersController@makeAdmin')->name('users.make-admin');
    Route::post('users/{user}/make-writer', 'UsersController@makeWriter')->name('users.make-writer');
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = ['name'];

    public function posts() // membantu untuk mengetahui jumlah post berdasarkan kategori
    {
        return $this->hasMany(Post::class);
    }

}

app/Http/Controllers/CategoriesController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use Illuminate\Http\Request;
use App\Http\Requests\Categories\CreateCategoryRequest;
use App\Http\Requests\Categories\UpdateCategoryRequest;

class CategoriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //dd(Category::first()->posts); // menampilkan array of object melalui collection
        //dd(Category::first()->posts()); // menampilkan relationship-nya
        //dd(Category::first()->posts()->where('published_at', now())->get()); // menampilkan collection saja
        //dd(Category::first()->posts()->where('published_at', now())); // menampilkan relationship-nya sekarang
        //dd(Category::first()->posts()->get()); // array of results (collection)
        //dd(Category::first()->posts());//array of results (collection) that belongs to this category

        return view('categories.index')->with('categories', Category::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateCategoryRequest $request)
    {
        //$this->validate(request()); // tidak efisien
        //$this->validate($request, [
        //    'name'=>'required|unique:categories'
        //]);


        //LEBIH AMAN MEMAKAI INI
        //$ncategory = new Category();
        Category::create([
            'name' => $request->name
        ]);

        session()->flash('success', 'Category created successfully.');

        /*TIDAK DISARANKAN MEMAKAI INI
        Category::create($request->all());
        */

        //return redirect('/categories');
        return redirect(route('categories.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category) // memakai route model binding
    {
        return view('categories.create')->with('category', $category);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateCategoryRequest $request, Category $category)
    {
        $category->update([
            'name' => $request->name
        ]);
        //$category->name=$request->name;
        //$category->save();

        session()->flash('success', 'Category updated successfully.');

        return redirect(route('categories.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        // mengecek apakah category memiliki post atau tidak
        if ($category->posts->count() > 0) {
            session()->flash('error', 'Category cannot be deleted, because there are posts related to it.');
            return redirect()->back();
        }

        $category->delete();

        session()->flash('success', 'Category delete successfully.');

        return redirect(route('categories.index'));
    }
}

resources/views/categories/create.blade.php
@extends('layouts.app')


@section('content')

    <div class="card card-default">
        <div class="card-header text-center">
            <h3>
            {{ isset($category) ? 'EDIT CURRENT CATEGORY' : 'CREATE NEW CATEGORY' }} <!-- isset dipakai karena kategori hanya akan tersedia ketika user memilih 'Edit' -->
            </h3>
        </div>
        <div class="card-body">

            @include('partials.errors')

            <form
                action="{{ isset($category) ? route('categories.update', $category->id) : route('categories.store') }}"
                method="POST">
                @csrf
                @if(isset($category))
                    @method('PUT')
                @endif
                <div class="form-group">
                    <label for="name"><b>Name</b></label>
                    <input type="text" id="name" class="form-control" name="name"
                           value="{{ isset($category) ? $category->name : '' }}">
                </div>

                <div class="form-group">
                    <button type="submit" class="btn btn-success mx-2" style="float: right;"><i class="fa fa-save"></i>
                        {{ isset($category) ? ' Finish Updating Category' : ' Finish Creating Category'}}
                    </button>
                </div>

                <div class="form-group">
                    <a href="{{ route('categories.index') }}" class="btn btn-dark mx-2" style="float: right;"><i class="fa fa-times"></i>
                        Cancel
                    </a>
                </div>

            </form>
        </div>
    </div>
@endsection

resources/views/categories/index.blade.php
@extends('layouts.app')


@section('content')

    <div class="d-flex justify-content-end">
        <!-- <a href="/categories/create" class="btn btn-success float-right mb-2">Add Category</a> -->
        <a href="{{ route('categories.create') }}" class="btn btn-success float-right mb-2"><i class="fa fa-plus"></i> Add Category</a>
    </div>

    <div class="card card-default">
        <div class="card-header">Categories</div>
        <div class="card-body">
            @if($categories->count()>0)
                <table class="table">
                    <thead>
                    <th>Categories Name</th>
                    <th>Total Posts</th>
                    <th>Action</th>
                    </thead>
                    <tbody>
                    @foreach($categories as $category)
                        <tr>
                            <td>
                                {{ $category->name }}
                            </td>
                            <td>
                                {{ $category->posts->count() }}

                                {{-- menampilkan array = {{ $category->posts }} --}}
                                {{-- perlu dd di CategoriesController bagian index = {{ $category->posts() }} --}}

                            </td>
                            <td>
                                <a href="{{ route('categories.edit', $category->id) }}" class="btn btn-info btn-sm"
                                   style="color:white"><i class="fa fa-edit"></i> Edit</a>

                                <!-- Pakai '$category->id' dikarenakan di tengah lokasinya ada '{category}', versi lengkapnya 'categories/{category}/edit' -->

                                <button class="btn btn-danger btn-sm" onclick="handleDelete({{ $category->id }})">
                                    <i class="fa fa-trash-o"></i>
                                     Delete
                                </button>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            @else
                <h3 class="text-center">No categories yet.</h3>
        @endif

        <!-- START MODAL EXAMPLE CODE -->

            <form action="" method="POST" id="deleteCategoryForm">
            @csrf
            @method('DELETE')
            <!-- Modal -->
                <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
                     aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="deleteModalLabel">Delete Category</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <p class="text-center text-bold">
                                    Are you sure to delete this category?
                                </p>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">No, go back.
                                </button>
                                <button type="submit" class="btn btn-danger">Yes, delete.</button>
                            </div>
                        </div>
                    </div>
                </div>

            </form>

            <!-- END MODAL EXAMPLE CODE -->

        </div>
    </div>
    </div>
@endsection

@section('scripts')
    <!-- JAVASCRIPT START -->
    <script>
        function handleDelete(id) {
            var form = document.getElementById('deleteCategoryForm')
            form.action = '/categories/' + id
            //console.log('Deleting', form)
            $('#deleteModal').modal('show')
        }
    </script>
    <!-- JAVASCRIPT END-->
@endsection